services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--username=admin", "--password=password", "--authenticationDatabase=admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./backend
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_venv:/app/.venv
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
      VITE_API_BASE_URL: http://localhost:8000
volumes:
  db_data:
  backend_venv:
  frontend_node_modules:
